parameters:
    vivait_logging_app_name: AcmeApp

services:
    vivait.logging_bundle.log_formatter:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.App%%] [%%extra.Environment%%] %%channel%%.%%level_name%%: %%message%% [%%extra.IP%%] [%%extra.UA%%] %%context%% %%extra%%\n"

    vivait.logging_bundle.log_processor:
        class: Vivait\LoggingBundle\Processor\LogProcessor
        arguments:
            - "@request_stack'
            - "%kernel.environment%"
            - "%vivait_logging_app_name%"
        tags:
            - { name: monolog.processor, method: processRecord }

    vivait.logging_bundle.event_listener.loggable:
        class: Vivait\LoggingBundle\EventListener\LoggableEventListener
        arguments:
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: '#', method: 'onEvent' }
